services:
  monitor:
    image: ghcr.io/zateckar/monitor:latest
    container_name: endpoint-monitor
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - monitor_data:/app/data
    environment:
      # Database configuration
      - DB_PATH=/app/data/db.sqlite
      
      # Security configuration
      - JWT_SECRET=${JWT_SECRET:-change-this-super-secret-jwt-key-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      
      # Default admin credentials
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin123}
      
      # Application configuration
      - NODE_ENV=production
      - PORT=3001
      - PRODUCTION_DOMAIN=${PRODUCTION_DOMAIN:-https://monitor.example.com}
      
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
        
volumes:
  monitor_data:
    driver: local
